name: Deploy Swagger
on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string
      swaggerFile:
        required: true
        type: string
    secrets:
      swaggerBucket:
        required: true
      awsRegion:
        required: true
      awsRoleToAssume:
        required: true
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure aws credentials # https://github.com/aws-actions/configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.awsRoleToAssume }}
          aws-region: ${{ secrets.awsRegion }}

      - name: Check if Swagger Exists
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: ${{ inputs.swaggerFile }}

      - name: Deploy swagger api to S3 bucket
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          aws s3 cp ${{ inputs.swaggerFile }} "$SWAGGER_BUCKET/${{ inputs.projectName }}/openapi3.json" --acl public-read
          aws s3 cp ${{ inputs.swaggerFile }} "$SWAGGER_BUCKET/${{ inputs.projectName }}/swagger.yaml" --acl public-read
        env:
          SWAGGER_BUCKET: ${{ secrets.swaggerBucket }}
