name: Deploy Swagger
on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string
      swaggerFile:
        required: true
        type: string
    secrets:
      swaggerBucket:
        required: true
      awsRegion:
        required: true
      awsAccessKeyId:
        required: true
      awsSecretAccessKey:
        required: true
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.5.5
        with:
          aws-access-key-id: ${{ secrets.awsAccessKeyId }}
          aws-secret-access-key: ${{ secrets.awsSecretAccessKey }}
          aws-region: ${{ secrets.awsRegion }}

      - name: Check if Swagger Exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ${{ inputs.swaggerFile }}

      - name: Deploy swagger api to S3 bucket
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          aws s3 cp ${{ inputs.swaggerFile }} "$SWAGGER_BUCKET/${{ inputs.projectName }}/openapi3.json" --acl public-read
          aws s3 cp ${{ inputs.swaggerFile }} "$SWAGGER_BUCKET/${{ inputs.projectName }}/swagger.yaml" --acl public-read
        env:
          SWAGGER_BUCKET: ${{ secrets.swaggerBucket }}
